// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt18AKEgiTAb29FQNIHmIvGp2B0omv2Qg',
    appId: '1:201271266109:web:8e60771b6e72f4ee9a9354',
    messagingSenderId: '201271266109',
    projectId: 'my-portfolio-cb170',
    authDomain: 'my-portfolio-cb170.firebaseapp.com',
    storageBucket: 'my-portfolio-cb170.firebasestorage.app',
    measurementId: 'G-3TZZLFXW4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9yja7TwoYPKzuIeWV0oO7sCpE0MOoR94',
    appId: '1:201271266109:android:81af9c3f1ccc3b8c9a9354',
    messagingSenderId: '201271266109',
    projectId: 'my-portfolio-cb170',
    storageBucket: 'my-portfolio-cb170.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAe4wKleaGhCGcNLt8KhCgRYFXcclGWaM',
    appId: '1:201271266109:ios:73eba7b59e7ef9b49a9354',
    messagingSenderId: '201271266109',
    projectId: 'my-portfolio-cb170',
    storageBucket: 'my-portfolio-cb170.firebasestorage.app',
    iosBundleId: 'com.example.rohitPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt18AKEgiTAb29FQNIHmIvGp2B0omv2Qg',
    appId: '1:201271266109:web:440c2da50dfef5959a9354',
    messagingSenderId: '201271266109',
    projectId: 'my-portfolio-cb170',
    authDomain: 'my-portfolio-cb170.firebaseapp.com',
    storageBucket: 'my-portfolio-cb170.firebasestorage.app',
    measurementId: 'G-QVJSJB00P4',
  );
}
